apiVersion: apps/v1
kind: Deployment
metadata:
  name: drpler-deployment
  labels:
    app: drpler
spec:
  selector:
    matchLabels:
      app: drpler
  replicas: 1
  template:
    metadata:
      labels:
        app: drpler
    spec:
      initContainers:
        - name: code
          image: wodby/drupal-php
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: code
              mountPath: /var/www/html
          command:
            - composer
            - create-project
            - drupal/recommended-project
            - .
      containers:
        - name: php
          image: wodby/drupal-php
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: code
              mountPath: /var/www/html
            - name: pvc
              mountPath: /var/www/html/web/sites/default/files
              subPath: public
        - name: nginx
          image: wodby/nginx
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NGINX_VHOST_PRESET
              value: "drupal10"
            - name: NGINX_BACKEND_HOST
              value: "localhost"
            - name: NGINX_SERVER_ROOT
              value: "/var/www/html/web"
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: code
              mountPath: /var/www/html
            - name: pvc
              mountPath: /var/www/html/web/sites/default/files
              subPath: public
      volumes:
        - name: code
        - name: pvc
          persistentVolumeClaim:
            claimName: drpler-pvc
