apiVersion: apps/v1
kind: Deployment
metadata:
  name: drpler
  labels:
    app: drpler
spec:
  selector:
    matchLabels:
      app: drpler
  replicas: 1
  template:
    metadata:
      labels:
        app: drpler
    spec:
      containers:
        - name: nginx
          image: wodby/nginx
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: code
              mountPath: /var/www/html
      volumes:
        - name: code
