apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.branchName }}-{{ .Values.appName }}-pvc
  labels:
    app: {{ .Values.branchName }}-{{ .Values.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi