apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.branchName }}-{{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.branchName }}-{{ .Values.appName }}
  type: LoadBalancer
  ports:
    - name: nginx
      protocol: TCP
      port: 80